<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/style.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/order/order.js')
    ->prependFile($this->basePath() . '/js/price-format.js')
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js')
    ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Store</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php if($this->zfcUserIdentity()): ?>
                    <?php if ($this->isAllowed('adminPanel')): ?>
                        <li><a href="/add">Add items</a></li>
                        <li><a href="/order/index">Orders</a></li>
                    <?php else: ?>
                        <li><a href="/order/indexUser">Orders</a></li>
                    <?php endif ?>
                <?php endif ?>
                <li><a href="/">Items</a></li>
                <?php if($this->isAllowed('cartPanel')): ?>
                    <li><a href="/order/currentOrder">Current order</a></li>
                <?php endif ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if($this->zfcUserIdentity()): ?>
                    <li>
                        <a href="#">
                            <?php echo $this->zfcUserIdentity()->getEmail(); ?>
                        </a>
                    </li>
                    <li>
                        <a href="/user/logout">
                            Logout
                        </a>
                    </li>
                <?php else: ?>
                    <li>
                        <a href="/user/login">
                            Login
                        </a>
                    </li>
                    <li>
                        <a href="/user/register">
                            Register
                        </a>
                    </li>
                <?php endif ?>
                <?php if($this->isAllowed('cartPanel')): ?>
                    <li>
                        <a href="<?php echo $this->url('order', array('action' => 'currentOrder')); ?>">
                            Count:
                            <span class="quantity"> <?php echo $this->cart->totalItems(); ?> </span>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('order', array('action' => 'currentOrder')); ?>">
                            T price:
                            <span class="sum"> <?php echo $this->cart->totalSum(); ?> </span>
                        </a>
                    </li>
                <?php endif ?>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    <?php echo $this->content; ?>
    <footer>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
